// Generated by CoffeeScript 2.3.2
(function() {
  var Config, Moon, SCALE, draw_grid, init, moons, pos_to_percent, redraw, svgDoc;

  SCALE = 5e7;

  Moon = require("./moon.js");

  Config = require("./config.js");

  moons = Moon.parse_moons();

  pos_to_percent = function(x) {
    var percent;
    // Get coord as percentage of scale
    percent = ((x / SCALE) + 1) * 50;
    return percent + "%";
  };

  draw_grid = function(svgDoc) {
    var i, j, results, x, y;
    // Draw grid
    svgDoc.append("line").attr("class", "grid-line-center").attr("x1", "0%").attr("x2", "100%").attr("y1", "50%").attr("y2", "50%");
    svgDoc.append("line").attr("class", "grid-line-center").attr("x1", "50%").attr("x2", "50%").attr("y1", "0%").attr("y2", "100%");
    for (y = i = 0; i < 20; y = ++i) {
      svgDoc.append("line").attr("class", "grid-line").attr("x1", "0%").attr("x2", "100%").attr("y1", y * 5 + "%").attr("y2", y * 5 + "%");
    }
    results = [];
    for (x = j = 0; j < 20; x = ++j) {
      results.push(svgDoc.append("line").attr("class", "grid-line").attr("x1", x * 5 + "%").attr("x2", x * 5 + "%").attr("y1", "0%").attr("y2", "100%"));
    }
    return results;
  };

  // Initialize SVG
  svgDoc = d3.select("body").append("svg");

  init = function() {
    $(document).on('keydown', function(e) {
      if (String.fromCharCode(e.which) === "Z") { // +
        SCALE *= 0.95;
        redraw();
      }
      if (String.fromCharCode(e.which) === "X") { // -
        SCALE /= 0.95;
        return redraw();
      }
    });
    // Draw grid
    draw_grid(svgDoc);
    svgDoc.append("div").text("Moon: ");
    return redraw();
  };

  redraw = function() {
    var paths, s;
    // Draw path
    // Remove all old paths
    svgDoc.selectAll("ellipse").remove();
    paths = svgDoc.selectAll("ellipse").data(moons);
    paths.enter().append("ellipse").attr("cx", function(m) {
      return `${-m.semimajor * m.ecc / SCALE * 50 + 50}%`;
    }).attr("cy", "50%").attr("rx", function(m) {
      return `${m.semimajor / SCALE * 50}%`;
    }).attr("ry", function(m) {
      return `${m.semiminor / SCALE * 50}%`;
    });
    // Draw moons
    svgDoc.selectAll("circle").remove();
    s = svgDoc.selectAll("circle").data(moons);
    s.exit().remove();
    return s.enter().append("circle").attr("r", function(m) {
      return 2;
    }).attr("fill", function(m) {
      return m.faction_color();
    }).transition().ease("constant").duration(100000).attrTween("cx", function(m) {
      return function(t) {
        return pos_to_percent(m.get_position_at_time(t * (Config["T1"] - Config["T0"]) + Config["T0"])[0]);
      };
    }).attrTween("cy", function(m) {
      return function(t) {
        return pos_to_percent(m.get_position_at_time(t * (Config["T1"] - Config["T0"]) + Config["T0"])[1]);
      };
    });
  };

  init();

}).call(this);
