// Generated by CoffeeScript 2.3.2
(function() {
  // Globals
  var DT, T0, T1;

  T0 = 0; // Time begin since alignment

  T1 = 27670; // Time end since alignment

  DT = 0.1;

  module.exports = {
    T0: T0,
    T1: T1,
    DT: DT
  };

}).call(this);
